name: My CD

on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: "Use Checkout Repo"
        uses: actions/checkout@v3
      - name: "Use fly"
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: "Deploy to flyio"
        run: flyctl deploy --remote-only --wait-timeout 3600
        env: 
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}