name: My CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**"
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Use Checkout Repo"
        uses: actions/checkout@v3
      - name: "Use Node.js 16.x"
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: "Install Package"
        run: yarn
      - name: "Build"
        run: yarn build
      - name: "Test"
        env:
          SECRET_MESSAGE: ${{ secrets.MY_SECRET_MESSAGE }}
        run: yarn test
      